<?php echo $this->doctype();?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $this->headTitle;?></title>                          
</head>
<body>
    <div>
        <?php echo $this->render('header.phtml') ?>
    </div>
    <div>
        <h2 style="text-alight:center;"><?php echo $this->titlePage;?></h2>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>