<h2>Add a person</h2>
<form method="post" action="/person/add">
<div class="form-group row">
    <label for="txtName" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      <input type="text" name="txtName" class="form-control" id="txtName" placeholder="Name">
    </div>
  </div>
  <div class="form-group row">
    <label for="txtAddress" class="col-sm-2 col-form-label">Address</label>
    <div class="col-sm-10">
      <input type="text" name="txtAddress" class="form-control" id="txtAddress" placeholder="Address">
    </div>
  </div>
  <div class="form-group row">
    <label for="txtAge" class="col-sm-2 col-form-label">Age</label>
    <div class="col-sm-10">
      <input type="text" name="txtAge" class="form-control" id="txtAge" placeholder="Age">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Create</button>
</form>