<h2>Edit a person</h2>
<form method="post" action="/person/edit?id=<?php echo $this->person->id;?>">
<div class="form-group row">
    <label for="txtName" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      <input type="text" name="txtName" class="form-control" id="txtName" value="<?php echo $this->person->name;?>" placeholder="Name">
    </div>
  </div>
  <div class="form-group row">
    <label for="txtAddress" class="col-sm-2 col-form-label">Address</label>
    <div class="col-sm-10">
      <input type="text" name="txtAddress" class="form-control" value="<?php echo $this->person->address;?>" id="txtAddress" placeholder="Address">
    </div>
  </div>
  <div class="form-group row">
    <label for="txtAge" class="col-sm-2 col-form-label">Age</label>
    <div class="col-sm-10">
      <input type="text" name="txtAge" class="form-control" value="<?php echo $this->person->age;?>" id="txtAge" placeholder="Age">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Edit</button>
</form>