<table class="table table-striped custab">
    <thead>
    <a href="/person/add" class="btn btn-primary btn-xs pull-right"><b>+</b> Add new person</a>
        <tr>
            <th>ID</th>
            <th>Fullname</th>
            <th>Address</th>
            <th>Age</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
	<?php 
	foreach ($this->persons as $row):?>
            <tr>
                <td><?php echo $row->id; ?></td>
                <td><?php echo $row->name; ?></td>
                <td><?php echo $row->address; ?></td>
                <td><?php echo $row->age; ?></td>
                <td class="text-center">
					<a class='btn btn-info btn-xs' href="/person/edit?id=<?php echo $row->id?>"><span class="glyphicon glyphicon-edit"></span> Edit</a> 
					<a href="/person/del?id=<?php echo $row->id;?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a>
				</td>
			</tr>
	<?php endforeach; ?>	
    
</table>